# -*- coding: utf-8 -*-
"""Logistic C.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kEASqaz_Hk8eTpTL0PV5jsySMD3B0fW9
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
# %matplotlib inline

df=pd.read_csv('Iris.csv')

from sklearn.preprocessing import LabelEncoder

df.drop('Id',inplace=True,axis=1)

df

X=df.drop('Species',axis=1)
y=df['Species']

y

y=LabelEncoder().fit_transform(y)

y

from sklearn.preprocessing import StandardScaler

ss=StandardScaler()

ss.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()

lr.fit(X_train,y_train)

from sklearn.metrics import accuracy_score

prediction=lr.predict(X_test)

print(accuracy_score(y_test,prediction)*100)

