# -*- coding: utf-8 -*-
"""Randomforest C.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cu9gqPE_jGxFnhpHo6PHIy5l-kafKq5_
"""

import pandas as pd
import numpy as np

df=pd.read_csv('Iris.csv')

df.drop('Id',axis=1,inplace=True)

df.head()

X=df.iloc[:,:4]
y=df.iloc[:,4]

X

y.head()

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

sns.displot(data=df['SepalLengthCm'],kde=True)

sns.displot(data=df['SepalWidthCm'],kde=True)

sns.displot(data=df['PetalLengthCm'],kde=True)

sns.displot(data=df['PetalWidthCm'],kde=True)

plt.figure(figsize = (10, 7))
sns.scatterplot(x = 'PetalLengthCm', y = 'PetalWidthCm', hue = 'Species', data = df)
plt.legend(bbox_to_anchor = (1, 1), loc = 2, fontsize = 15)
plt.title('Petal Length VS Petal Width', fontsize = 20)
plt.xlabel('Petal Length', fontsize = 15)
plt.ylabel('Petal Width', fontsize = 15)
plt.show()

plt.figure(figsize = (10, 7))
sns.scatterplot(x = 'SepalLengthCm', y = 'SepalWidthCm', hue = 'Species', data = df)
plt.legend(bbox_to_anchor = (1, 1), loc = 2, fontsize = 15)
plt.title('Sepal Length VS Sepal Width', fontsize = 20)
plt.xlabel('Sepal Length', fontsize = 15)
plt.ylabel('Sepal Width', fontsize = 15)
plt.show()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

from sklearn.ensemble import RandomForestClassifier

rc=RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 0)

rc.fit(X_train,y_train)

pre=rc.predict(X_test)

from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(pre,y_test))

print(classification_report(y_test, pre))

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,pre)*100)

