# -*- coding: utf-8 -*-
"""XGboost C.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qcIbQZkIqFilLPYbQj0GbIUuX7wfOsz6
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
# %matplotlib inline

df=pd.read_csv('Iris.csv')

df.head()

plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
sns.distplot(df['SepalLengthCm'])
plt.subplot(1,2,2)
sns.distplot(df['SepalWidthCm'])
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
sns.distplot(df['PetalLengthCm'])
plt.subplot(1,2,2)
sns.distplot(df['PetalWidthCm'])

from xgboost import XGBClassifier

cf=XGBClassifier()

df.drop('Id',axis=1,inplace=True)

from sklearn.model_selection import train_test_split

X=df.drop(['Species'],axis=1)
y=df['Species']

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

y=le.fit_transform(y)

y

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.33, random_state=42)

cf.fit(X_train,y_train)

prediction=cf.predict(X_test)

from sklearn.metrics import accuracy_score

print(accuracy_score(prediction,y_test))

from sklearn.metrics import confusion_matrix

print(confusion_matrix(prediction,y_test))

